### ISSUE TITLE
Status of simulations

### ISSUE THREAD

**Issue by dargueso** [matthiasdemuzere/wrf-lcz-KL#12]
The current status of the experiments is:

NoUrban (natural landscape): running 75% complete - all boundary conditions generated
LCZ extent (no city heterogeneity): running 10% complete - all boundary conditions generated
LCZ param (city heterogeneity): not running yet - boundary conditions to be generated. 

I will send the LCZ param experiment boundary conditions to @andreazonato as soon as possible to check they are OK.

**Comment by matthiasdemuzere** [comment]
Thanks for the update @dargueso. Nice to see Exp. B is now also up and running ...

I still would like to check the PARAM.LCZ.TBL for Exp. C., to see the values that are used in there. I will try to do so tomorrow, I hope I don't forget.

**Comment by dargueso** [comment]
I can't get the Boundary conditions done with the geo_em.d02_LCZ_params.nc file. There seem to be a field that WPS cannot properly read. I'm still trying to figure out what's wrong.

**Comment by matthiasdemuzere** [comment]
Ha, that's too bad. Please let me know if I can be of help / need to change something in my conversion script ...

**Comment by dargueso** [comment]
As I commented at the beginning, one the issues with running these experiments is the storage. We're running very low right now here at our department. I can optimise the outputs by deleting all files for domain 1, which we're not interested in (in principle). We can keep them for one of the experiments only, since they should be exactly the same, at least in terms of their configuration - domain2 does not affect domain1 since we're using one-way nesting. I'm aware that they can be slightly differ due to computational factors, but I wouldn't worry about that. What do you think? Do you have any particular interest in keeping them all?

**Comment by matthiasdemuzere** [comment]
Sounds like a good strategy to me!

**Comment by dargueso** [comment]
Ok, so I've started again exp B with v4.3 using BEP+BEM and the latest version of the geo_em file (v6).
As far as I can tell, I can also start exp C with the URBPARM file you sent ([here](https://github.com/wrf-model/WRF/blob/f4f83984357b021062e6ff94a21fe7aac3e9937b/run/URBPARM_LCZ.TBL))  and the corresponding geo_em (v6, LCZ params), right? 

I think we should start closing issues and create a general discussion one, because I get lost every time I need to read and reply. What do you think? That we we can keep specific topics within issues and then a general thread with all general interactions. Although I hope we won't have to open many more issues!

**Comment by andreazonato** [comment]
Yes, in my opinion, BEP+BEM for exp B) and C) is the best solution we have.
Yes, we should close all issues and hopefully BEP+BEM will run without any problem for exp C) too. Actually I'm pretty sure it will work, since this current WRF version works good in all cases we tested before to be released.
