### ISSUE TITLE
values URBPARAM_LCZ.TBL

### ISSUE THREAD

**Issue by matthiasdemuzere** [matthiasdemuzere/wrf-lcz-KL#14]
@andreazonato:

I have been looking a bit into the values designated to all parameters.
It is clear that many of these parameters are not reported in any of Stewarts previous works, so a best-guess has to be made.

Yet I do wonder about some, eg:
- AHF for LCZ 11 (15): set to 350Wm2 by default (same as for Heavy Industry). Since this class reflects paved areas (eg. parking lots), I would rather set this default value to 0?
- AHL: same remark for the latent anthropogenic heat flux?

(I do realize AHF is by default turned of having AHOPTION: 0)

- Radiative and thermal parameters. In Stewart et al. (2014), many parameter values are described in their Tables A2.1 and A2.2. Yet since values were not always available per facet, I contacted Iain and Scott to obtain these values. The values we currently use in the WUDAPT-to-COSMO routine are based on those. Have a look at the table [here](https://github.com/matthiasdemuzere/WUDAPT-to-COSMO/blob/master/tables/LCZ_UCP_default.xlsx). So this table provides info for albedo, emissivity, heat capacity and conductivity for roof, wall and road. 

So I guess the question is: should we alter values in `URBPARAM_LCZ.TBL` to make it more consistent (also with other resources), or leave it as such?

Yet since  `URBPARAM_LCZ.TBL` not really has to be part of our w2w.py package (it uses an internal LCZ_UCP look up table, [here](https://github.com/matthiasdemuzere/wrf-lcz-KL/blob/main/LCZ_UCP_default.csv)), this is probably a more general question for the WRF release ...

**Comment by matthiasdemuzere** [comment]
I can adjust the parameter values based on the values from published works. Does this mean that this new "default" table would make it then to the official WRF release?

And of course I agree, if people have better values for their city, they should use them. Yet better to have the default really as the default. This makes sense for our KL case already, as we have no other reference values, so better use what is assumed to be universal ...

I will make a new version of the table, and upload it here ....

**Comment by andreazonato** [comment]
The WRF version have been released something like 18 hours ago...I do not think it is possible to substitute it now, but I can ask them... However, once you will release the new tool, we can add the "default" table so people can use it in a sort of "standard" way, even if we know there is no a standard for all the cities in the world...

**Comment by matthiasdemuzere** [comment]
yeah, but the thing is they would need to copy this table to the appriopriate WRF folder manually, no?
So ideally a small push to this new release would be ideal? I assume [this](https://github.com/wrf-model/WRF/releases) is the repo, no?

Otherwise I am afraid that this "default table" would go unused if it's just embedded within our w2w routine?

**Comment by andreazonato** [comment]
Yes, It is as you say. I'm writing an NCAR developer to fix the issue.
