### ISSUE TITLE
fine tune HI_URB2D

### ISSUE THREAD

**Issue by matthiasdemuzere** [matthiasdemuzere/wrf-lcz-KL#18]
When testing the tool over Zaragoza, @albertomartilli found the building height distributions [0-75m] in URB_PARAM inconsistent with the corresponding LCZ class.

His comment:

Still looking around in some point sof the fiel you sent for Zaragoza, I see that the mean building height is not at the center of the distribution.

For example, the point class 32 (i=80, j=48) has a mean building hieght of 15.09m, and the distribution is  6.69% of 5m, and 93.31% at 10m. Am I missing something?

**Comment by matthiasdemuzere** [comment]
Fixed in #19

**Comment by matthiasdemuzere** [comment]
@dargueso: revised files for our Kuala Lumpur experiment are available [here](https://drive.google.com/drive/folders/1KT3hWza_WFUc_wL7qxfFUltVZ4iKj68P?usp=sharing). Can you confirm you have received the files?

Let's hope these work without any further issues ...

**Comment by matthiasdemuzere** [comment]
@albertomartilli [just moving this comment here, under the issues section].

> Looks good now at first look, thanks! Most of the buildings are between 15 and 20m, which is reasonable, and mean building height is up to 15m.
> Yes, I understood the averaging over all the classes within the grid cell.

Great.
> Form the point of view of model efficiency (both in terms of memory storage and speed), we could probably neglect small percentages, but this is something we can manage at code level.

Good point. Yet perhaps it is better to do this within this code, so that future users of this tool will not have to change the BEP+BEM source code. What would you suggest? Set e.g. values < 5% to 0? 

I was also wondering whether the float type will influence the computation? Perhaps we could set the % to integers, as the current precision is not needed? This thinking is a bit in line with the wider move from double to single or even half precision in current climate models (see eg. [this recent work from ECMWF](https://arxiv.org/pdf/2104.15076.pdf)).

> 
> I like the sigma approach for building heigths, Maybe we should use it also for the URBPARM_LCZ.TBL and homogenize it with your look-up table,

You mean to alter the values in URBPARAM_LCZ.TBL based on the values produced with our approach? That could also be a good idea, to make all more consistent. Yet, I do not fully understand how the intervals in that table are defined, they seem not to follow the 5m interval?

If we do this, we probably should also set ZR and SIGMA_ZED to the default values I use in my table, to have all consistent?

**Comment by albertomartilli** [comment]
Set values less than 5% to zero is a good option. This is relevant mainly if you use BEM. The code simulates the full Building Energy for every building with a percentage greater than zero, and then weight the fluxes using the percentages. For example for the point you mention, it would simulate 5 buildings (5m, 10m, 15m, 20m and 25m), but likely the impact of the 5m building (1.7%) and 25m (4.1%) will be almost negligible. If we put to zero the percentages less than 5, the results will be almost the same, but it will simulate only 3 buildings (10m, 15m, and 20m) - so less CPU time used and less memory storage. It would be good if you can extract also the maximum "number of percentges greater than 5" over all the grid points, because this is a parameter we have to fix in WRF.

The number of digits I think it is not very relevant for the CPU. For the storage, to have an effect I should change in WRF all the related variables form real to integer. For the moment I do not think it is worth.

Re the values of the building heigths in the actual URBPARM_LCZ.TBL, with Andrea we also noticed that they are not following the 5m interval, as they should, so we will ask NCAR to modfiy this.

One thing I did not understood from your program: when you define the mean, max and min building heights (based on Stewart and Oke, I suppose), what kind of percentage do you give to the three? Or what's the width of the gaussian distribution?
With this we can set the same distribution in the URBPARM_LCZ.TBL

**Comment by matthiasdemuzere** [comment]
> Set values less than 5% to zero is a good option. This is relevant mainly if you use BEM. The code simulates the full Building Energy for every building with a percentage greater than zero, and then weight the fluxes using the percentages. For example for the point you mention, it would simulate 5 buildings (5m, 10m, 15m, 20m and 25m), but likely the impact of the 5m building (1.7%) and 25m (4.1%) will be almost negligible. If we put to zero the percentages less than 5, the results will be almost the same, but it will simulate only 3 buildings (10m, 15m, and 20m) - so less CPU time used and less memory storage. 

Ok, I can implement this filter in my code.

> It would be good if you can extract also the maximum "number of percentges greater than 5" over all the grid points, because this is a parameter we have to fix in WRF.

This I do not understand yet. Could you clarify? We could also talk about this during our call.
> 
> The number of digits I think it is not very relevant for the CPU. For the storage, to have an effect I should change in WRF all the related variables form real to integer. For the moment I do not think it is worth.

Ok. We can leave it as is for the moment.
> 
> Re the values of the building heigths in the actual URBPARM_LCZ.TBL, with Andrea we also noticed that they are not following the 5m interval, as they should, so we will ask NCAR to modfiy this.

I aleady pushed an updated version of URBPARM_LCZ.TBL to the official github (see [here](https://github.com/wrf-model/WRF/pull/1520)). Once I understand how the values in this file should be structured, I don't mind updating this again.

> 
> One thing I did not understood from your program: when you define the mean, max and min building heights (based on Stewart and Oke, I suppose), what kind of percentage do you give to the three? Or what's the width of the gaussian distribution?
> With this we can set the same distribution in the URBPARM_LCZ.TBL

Yes, so I took default values for min, mean, max from Iain his work. The standard deviation I took from the URBPARM file.
Using these 4 properties, I can create a normal distribution, that is within the given bounds (see lines [here](https://github.com/matthiasdemuzere/wrf-lcz-KL/blob/9ea5ed2297172e0bf88be39b16720065ce730501/w2w.py#L489-L498)). 

Yet since the original STD value from URBPARAM did not allow me to make a normal distribution within the given min/max bounds, I adjusted some of those a little bit (for LCZs 1, 4 and 7 if I remember well).

Once the normal distribution is created, I bin then into the 5m bins, and convert them to percentages. 

Some examples of how these "truncated normal distributions" in python work are [here](https://stackoverflow.com/questions/36894191/how-to-get-a-normal-distribution-within-a-range-in-numpy).

**Comment by matthiasdemuzere** [comment]
@albertomartilli: the 5% filtering has been applied. See email for updated file.

@dargueso: I again re-processed the KL files as well, you can download them from [w2w_v6 in my google drive](https://drive.google.com/drive/folders/1pWNeWGAkbhL8lUeW6ZL3GK2RSuKaKcGu?usp=sharing).

**Comment by dargueso** [comment]
Thanks so much @albertomartilli and @matthiasdemuzere for working on the tool and fine tuning the geo_em files!

PD: Hi @albertomartilli, nice to "see" you again!

**Comment by albertomartilli** [comment]
Hi Daniel!


nice to get in touch with you again, let see if we can do some work together...


Alberto Martilli

Air Quality Modelling Group

CIEMAT,

Madrid, Spain

https://www.researchgate.net/profile/Alberto-Martilli

________________________________
De: Matthias Demuzere ***@***.***>
Enviado: domingo, 23 de mayo de 2021 8:43:19
Para: matthiasdemuzere/wrf-lcz-KL
Cc: Martilli, Alberto; Mention
Asunto: Re: [matthiasdemuzere/wrf-lcz-KL] fine tune HI_URB2D (#18)


@albertomartilli<https://github.com/albertomartilli>: the 5% filtering has been applied. See email for updated file.

@dargueso<https://github.com/dargueso>: I again re-processed the KL files as well, you can download them from w2w_v6 in my google drive<https://drive.google.com/drive/folders/1pWNeWGAkbhL8lUeW6ZL3GK2RSuKaKcGu?usp=sharing>.
