### ISSUE TITLE
Preparing Natural and Default simulations. 

### ISSUE THREAD

**Issue by dargueso** [matthiasdemuzere/wrf-lcz-KL#2]
Everything ready to run the natural (urban replaced with surrounding dominant land-use) and default simulations .

A couple of questions before I move on:

1) Did we finally agree on the 2008-2012 (like the previous paper) or 2016-2020 (most updated ERA5)? I think we said the last one, but just to make sure before starting the runs.

2) I will also run the default run with the land-use from MODIS. Matthias, did you want to extend the city in the default run to the LCZ extension? Or clip the LCZ to the default? 

3) We don't have much space for storage here and these runs are going to take quite a lot of space. So I will remove most of the 4D fields from the outputs and write them out every 3 hours. I will keep the essential ones to derive temperature, pressure, humidity and winds. If you want to keep something else, please let me know. Most 3D fields (surface fields) will be kept at hourly frequency and only fields specific to certain schemes will be removed.

Thanks

**Comment by matthiasdemuzere** [comment]
Great news!

> * Did we finally agree on the 2008-2012 (like the previous paper) or 2016-2020 (most updated ERA5)? I think we said the last one, but just to make sure before starting the runs.

I am indifferent here. Both have (dis)advantages. I'll leave the decision up to you.

> * I will also run the default run with the land-use from MODIS. Matthias, did you want to extend the city in the default run to the LCZ extension? Or clip the LCZ to the default?

I don't have the LCZ map yet, so I do not know yet how much different the urban extent is compared to the one from MODIS. 
Could you wait a bit longer to start this run, so that I have time to figure this one out?

> * We don't have much space for storage here and these runs are going to take quite a lot of space. So I will remove most of the 4D fields from the outputs and write them out every 3 hours. I will keep the essential ones to derive temperature, pressure, humidity and winds. If you want to keep something else, please let me know. Most 3D fields (surface fields) will be kept at hourly frequency and only fields specific to certain schemes will be removed.

Sounds reasonable to me. First goal is of course to see whether a more detailed urban description changes the precipitation response (so surface field). Hourly values are of course critical for this. 4D fields could be useful in a subsequent analysis to understand any of the differences. Keeping the essential ones as listed above 3-hourly might do the trick already (if we ever manage to perform this more detailed analysis)

**Comment by dargueso** [comment]
Sounds good. I will go for the 2016-2020 period, being aware of the disadvantages. The original runs were ERA-Interim, so they are not exactly comparable anyway.

Yes, I can wait and hold the default one. I'll go with the natural one in the meantime.

I'm keeking precipitation at higher frequency (10min), which I think it could be nice to study changes in intensity. All the rest at hourly, except the selected 4D fields at 3 hourly. Not sure yet if I will keep domain1 (coarser resolution) outputs. I will write them out following the approach above for now, and decide later on depending on the storage available.

**Comment by matthiasdemuzere** [comment]
Hi @dargueso,

I have been working a bit on the LCZ-based urban extent for the "Default" run.
Some notes are available [here](https://github.com/matthiasdemuzere/wrf-lcz-KL#implement-lcz-information).

Resulting file is under: Data > geo_em.d02_LCZurban.nc.
In this file, LU_INDEX = 13 refers to the aggregated (mode) LCZ pixels belonging to built LCZ classes 1 to 10.

Can you have a look if the format of this resulting .nc file is correct?
