### ISSUE TITLE
number of percentges greater than 5

### ISSUE THREAD

**Issue by matthiasdemuzere** [matthiasdemuzere/wrf-lcz-KL#22]
Feature requested by @albertomartilli:

It would be good if you can extract also the maximum "number of percentges greater than 5" over all the grid points, because this is a parameter we have to fix in WRF.

Could you perhaps elaborate a bit more what you mean by this @albertomartilli? Then I can have a look ....

**Comment by albertomartilli** [comment]
For example in the grid point we refer to for Zaragoza, there are "3 height percentages" different than zero, e. g. buildings of 10, 15 and 20m. IN another grid point you may have a different amount of "percentages different than zero", for example 4 if you have buildings of 5m, 10m, 15m, and 20m. What I need is to extract the "maximum amount of percentages different than zero" over all the grid points. There may be a much simpler way to express this, but I can find it now. Let me know if it is clear

**Comment by matthiasdemuzere** [comment]
Ok, so per grid cell the number of 5m height bins that are not zero? Correct?

Should this field be included in the resulting netcdf file? If so, what should be its variable name (and other metata such as long name, description etc)? Or do you want this in another format?

Just let me know @albertomartilli, I can then see how to implement this ...

**Comment by albertomartilli** [comment]
Not the field, just one number - the maximum value over all the urban grid points. This is a number I can put in wrf to optimize the memory storage. By default it's 15, but if we can reduce it we will save memory

**Comment by matthiasdemuzere** [comment]
ha, ok. 

This table below already gives a first hint of course, with a maximum of 4 different bins that contain values greater than 5%.
[df_hi.csv](https://github.com/matthiasdemuzere/wrf-lcz-KL/files/6541724/df_hi.csv).

Of course, the lcz-resolution averaging could lead to a different number, yet I assume it will never be much more than this?

But I can add this information. 

Perhaps I could add it as a global attribute (see list below), with a new attribute name, eg. MAX_HI_INTERVAL?

![image](https://user-images.githubusercontent.com/6926916/119554585-21d42b00-bd9d-11eb-99ca-480942e0587e.png)

**Comment by albertomartilli** [comment]
this is a parameter that we need at compilation time, and not at run time. But it is OK if you add it as global attribute, so people can check in the netcdf with a simple ncdump.
If you do it, call it "nbui_max" which is the name of this parameter in wrf.
Thanks

**Comment by matthiasdemuzere** [comment]
Hi @albertomartilli,

I have added the value now as a global attribute. This is for the Zaragoza case (ndui_max = 4):

![image](https://user-images.githubusercontent.com/6926916/119671299-f5222100-be39-11eb-96cf-bf58b36364e3.png)

Note that hen the w2w routine is executed, this information is also provided in the terminal:

![image](https://user-images.githubusercontent.com/6926916/119671440-0c610e80-be3a-11eb-994a-08ce5c956e19.png).

The update file is available [here](https://drive.google.com/file/d/1N7CfKYBcD0OyibUvR6BN_qEmXSsEtNCG/view?usp=sharing).

**Comment by albertomartilli** [comment]
perfect, thanks!


During our meeting of the 2nd of june, can you explain us how to use your python code, and provide it to us, or it is too early?


A.


Alberto Martilli

Air Quality Modelling Group

CIEMAT,

Madrid, Spain

https://www.researchgate.net/profile/Alberto-Martilli

________________________________
De: Matthias Demuzere ***@***.***>
Enviado: miércoles, 26 de mayo de 2021 15:55:14
Para: matthiasdemuzere/wrf-lcz-KL
Cc: Martilli, Alberto; Mention
Asunto: Re: [matthiasdemuzere/wrf-lcz-KL] number of percentges greater than 5 (#22)


Hi @albertomartilli<https://github.com/albertomartilli>,

I have added the value now as a global attribute. This is for the Zaragoza case (ndui_max = 4):

[image]<https://user-images.githubusercontent.com/6926916/119671299-f5222100-be39-11eb-96cf-bf58b36364e3.png>

Note that hen the w2w routine is executed, this information is also provided in the terminal:

[image]<https://user-images.githubusercontent.com/6926916/119671440-0c610e80-be3a-11eb-994a-08ce5c956e19.png>.

The update file is available here<https://drive.google.com/file/d/1N7CfKYBcD0OyibUvR6BN_qEmXSsEtNCG/view?usp=sharing>.

**Comment by matthiasdemuzere** [comment]
Let me address this in an email, including Alejandro.

I will close this issue now, as it is done.
