### ISSUE TITLE
WRFV4.3 BEP+BEM restarts

### ISSUE THREAD

**Issue by dargueso** [matthiasdemuzere/wrf-lcz-KL#23]
Hi all, 
I've got issues with Exp B (Exp C hasn't started yet) when writing the restart out. 
The model seems to run well, but after writing the restart it freezes. As usual, it doesn't give any clarifying error message. I've tried to write restarts at different frequencies to isolate the problem, and it always freezes right after writing out the restart file, no matter when we write it out. 
Those restart files are useless, by the way, since WRF is unable to restart from them. They seem to be corrupted since they are significantly smaller than the Exp A restarts.

Any clues @andreazonato or @albertomartilli?
It could be their size...so I am trying to split them and create one restart file per processor.

**Comment by albertomartilli** [comment]
Hi Dani,
not sure, I usually do not do restarts. My runs are at the best one week-10 days, so I do not restart them. Anything strange in the fields before it crashes at the tiem when it writes the restart? Do you really need restarts?

**Comment by dargueso** [comment]
@albertomartilli, we're running 5 years, so we need to use restarts. There's no way to fit jobs in the queues if the simulations exceed 15 days or so. I'm checking the restarts, but all I can see is that they aren't complete. Still checking.

**Comment by matthiasdemuzere** [comment]
Good luck with this @dargueso.

When I was emailing with one of the WRF code maintainers (Cenlin He - cenlinhe@ucar.edu) about the update of the URBPARAM_LCZ table, he also mentioned the following:

> Matthias, regarding the urban restart issue, if you want to know more about it, please let Andrea or myself know. We are still trying to figure out the bug. Briefly, the new BEP+BEM code does not show a consistent result between continuous run and restart run.

While different from your error, perhaps you could reach out to him also to ask for support? Unless of course @andreazonato has ideas on how to solve this?

**Comment by albertomartilli** [comment]
5 years..are you kidding, right ;-). In any case I just tried and in my case with the new version, the code does not stop when it writes a restart. I didn't know about the problem mentioned by Cenlin above, given that as I said I usually do not use restart.
I think it is worth to contact him - if you do it, please put me in cc, since I'd like to know

**Comment by dargueso** [comment]
Thanks for your feedback. I have solved the problem for exp B. Apparently, It was an issue with the size of the restart. Running with one domain only solved it. Then splitting the restart files one per processor, thus making restart files much smaller, also fixed the problem. So now it is running with this latter option. Let see if it works for exp C too.

Having said that, it is interesting what Cenlin mentioned...Unfortunately we cannot work without restarts give the length of the runs.

**Comment by andreazonato** [comment]
Dear all,

the problem Cenlin mentioned is about the green-roof+PVP parameterizations, so it is not important in our case. 
@dargueso, I've no idea about the problem sincerelly. Can it be related to the fact that you print additional variables in the Registry? Is it giving you some error into the rsl*?

**Comment by andreazonato** [comment]
I tried the new code with the restarts...and it works in my cases too. Did you try with the "old" version, i.e the pre-release I sent you before the new WRF 4.3 came out?

**Comment by dargueso** [comment]
Thanks all, problem solved. As I mentioned, it was an issue with the size of the restart files. Now it works for exp C too.
