### ISSUE TITLE
Boundary conditions

### ISSUE THREAD

**Issue by oscarbrousse** [matthiasdemuzere/wrf-lcz-KL#25]
Previous work over Madrid showed that urban pixels located close to the boundaries can make the model explode when BEP-BEM is activated. Possible explanations were related to heat and kinetic energy transport. We did not investigate it at the time but removing the urban pixels for a certain amount of pixels located close to the boundary allowed the model to work well.

Possible switch to add to the w2w.py script would be to have the users deciding to remove urban pixels close to the boundaries of the inner domain and to chose the amount of pixels to mask out (eg. 10 to 20 looks like an optimal default choice).

These pixels could be the same as the default _NoUrban case and FRC_URB2D and URBPARAM set to 0.

**Comment by matthiasdemuzere** [comment]
Hi @oscarbrousse

I have given this some thought, and decided not to implement this. Reasons?

As far as I understand, this is a behaviour you encountered quite some time ago, with a different WRF version (3.2?)
As such, we do not know if this problem still persists in the current version. 
Therefore I would only like to respond to things only when do they occur.

I will close this issue for now. Yet in case such behaviour would pop-up again, we'll know how to address it.
