### ISSUE TITLE
Construct URB_PARAM matrix

### ISSUE THREAD

**Issue by matthiasdemuzere** [matthiasdemuzere/wrf-lcz-KL#5]
Let's start a new issue to discuss everything related to the URB_PARAM matrix.

So according to the user guide, one needs entries in blue and purple for the single layer / all urban parameterization schemes. These include (based on input of @andreazonato):

**FRC_URB2D** (sepatate from the URBPARAM matrix) -> Fraction of impervious surface with respect to total area

Next variables should be put inside the variable URB_PARAM at different nz levels.

**LP_URB2D**=URB_PARAM(nx,91,ny) Plan area fraction of buildings
**MH_URB2D**=URB_PARAM(nx,92,ny) Mean buildings heights
**STDH_URB2D**=URB_PARAM(nx,93,ny) Standard Deviation of buildings heights
**HGT_URB2D**=URB_PARAM(nx,94,ny) Area Weighted mean buildings heights
**LB_URB2D**=URB_PARAM(nx,95,ny) TOTAL area fraction of buildings (frontal+plan)
**LF_URB2D**=URB_PARAM(nx,96 to 99,ny) Frontal area Index in N,E,S,W directions respectively (for WUDAPT LCZs they should be all equal)

I'll start with this now, and post questions here in case they occur ...

**Comment by matthiasdemuzere** [comment]
@andreazonato:

**FRC_URB2D**, is that the same as **FRC_URB** in URBPARM_LCZ.TBL?
If so, the assigned values are in my opinion not correct?

For now I'll be working with a separate look-up table (based on the one I compiled for COSMO from Stewart and Oke (2012) and Stewart et al. (2014). We can afterwards see what variables and values are different ...

**Comment by matthiasdemuzere** [comment]
@andreazonato:

Where can I find the values for HGT_URB2D? And what exactly does this variable mean?

**Comment by matthiasdemuzere** [comment]
@andreazonato:

On a more general note, that might refer to my previous question:

Are the UCPs not weighted by ISA when aggregating from the high to the coarse resolution? See example here:
![image](https://user-images.githubusercontent.com/6926916/115543803-13788800-a2a2-11eb-9cbd-f486fda6db33.png)

This is something we do in the WUDAPT-TO-COSMO conversion (except for ISA, which is FRC_URB2D in WRF), in order to conserve the city characteristics after remapping to coarser resolution. 

I my opinion this should be applied here as well?

**Comment by matthiasdemuzere** [comment]
@andreazonato:

Just to be sure. The index values you provide (91, 92, ...) are fortran-based, no? Meaning they start at position 1? 
This is important, since python starts at 0, so I have to makes sure to put them at the right place ...

**Comment by andreazonato** [comment]
> @andreazonato:
> 
> **FRC_URB2D**, is that the same as **FRC_URB** in URBPARM_LCZ.TBL?
> If so, the assigned values are in my opinion not correct?
> 
> For now I'll be working with a separate look-up table (based on the one I compiled for COSMO from Stewart and Oke (2012) and Stewart et al. (2014). We can afterwards see what variables and values are different ...

Yes, FRC_URB2D is FRC_URB in URBPARM_LCZ.TBL. You can change it inside the URBPARM, these are values I assigned to my LCZ  here in Italy. You can change them

**Comment by andreazonato** [comment]
> @andreazonato:
> 
> Where can I find the values for HGT_URB2D? And what exactly does this variable mean?

These are the building heights, where the average within the same cell is made weighting based on the area of the buildings. However in my opinion a simple average can work

**Comment by andreazonato** [comment]
> @andreazonato:
> 
> On a more general note, that might refer to my previous question:
> 
> Are the UCPs not weighted by ISA when aggregating from the high to the coarse resolution? See example here:
> ![image](https://user-images.githubusercontent.com/6926916/115543803-13788800-a2a2-11eb-9cbd-f486fda6db33.png)
> 
> This is something we do in the WUDAPT-TO-COSMO conversion (except for ISA, which is FRC_URB2D in WRF), in order to conserve the city characteristics after remapping to coarser resolution.
> 
> I my opinion this should be applied here as well?

That's exactly what we need. In my opinion thats not fundamental, but better if we have it

**Comment by andreazonato** [comment]
> @andreazonato:
> 
> Just to be sure. The index values you provide (91, 92, ...) are fortran-based, no? Meaning they start at position 1?
> This is important, since python starts at 0, so I have to makes sure to put them at the right place ...

Yes, they are fortran based, so 1 to 132. Values I put in the instructions are fortran suited. In any case, when you'll visualize them with ncview, they will be 0 to 132-1, because ncview works like python

**Comment by matthiasdemuzere** [comment]
@andreazonato:

And where can I find the values for **LB_URB2D** and **LF_URB2D**? So the total and frontal area fractions?

**Comment by andreazonato** [comment]
https://ars.els-cdn.com/content/image/1-s2.0-S221209551930183X-gr4_lrg.jpg

The first row is LB_URB2D. LB_URB2D is basically LP_URB2D (horizontal area fraction)+LF(the frontal area fraction)

**Comment by matthiasdemuzere** [comment]
> https://ars.els-cdn.com/content/image/1-s2.0-S221209551930183X-gr4_lrg.jpg
> 
> The first row is LB_URB2D. LB_URB2D is basically LP_URB2D (horizontal area fraction)+LF(the frontal area fraction)

Uhm, ok, but I can not derive the actual values from that Figure no? As I can not see them in URB_PARAM.TBL_LCZ, I wonder where the actual values are?

**Comment by andreazonato** [comment]
There are two possibilities to estimate these values for each LCZ.

1) directly take them from  Stewart and Oke (2012)

2) assign to each LCZ a value for h(building height distribution) b(building width) and w(street width) and then calculate them as=

lambda_p=b/(b+w)
lambda_f=2*h/(b+w) (that's an estimation, in my paper I use this formula)
lambda_b=lambda_p+lambda_f

**Comment by matthiasdemuzere** [comment]
> There are two possibilities to estimate these values for each LCZ.
> 
> 1. directly take them from  Stewart and Oke (2012)
> 2. assign to each LCZ a value for h(building height distribution) b(building width) and w(street width) and then calculate them as=
> 
> lambda_p=b/(b+w)
> lambda_f=2*h/(b+w) (that's an estimation, in my paper I use this formula)
> lambda_b=lambda_p+lambda_f

Ha, I  see. I thought there existed a pre-compiled set of values. Seems not, good to know. Will see how to integrate these then ... Thanks.

**Comment by matthiasdemuzere** [comment]
> 1. directly take them from  Stewart and Oke (2012)
> 2. assign to each LCZ a value for h(building height distribution) b(building width) and w(street width) and then calculate them as=
> 
> lambda_p=b/(b+w)
> lambda_f=2*h/(b+w) (that's an estimation, in my paper I use this formula)
> lambda_b=lambda_p+lambda_f

@andreazonato:

Perhaps you can help me out witth these 2 variables a bit.

1. Stewart and Oke (2012) do not have any information on the frontal area or total area index in their tables?
The only thing useful is their aspect ratio H/W, as we can get W from that, since we know H.

So that leaves a decision on building width. Not sure how to guess this one? I also don't really see fro your paper what values you used?

Or do you use those from the URB_PARAM_LCZ.TBL table (assuming the first column is the LCZ class)?

![image](https://user-images.githubusercontent.com/6926916/115612607-bf929100-a2eb-11eb-965c-d6573581c02b.png)

If so, I can also continue to work with those ...

**Comment by andreazonato** [comment]
Yes, exactly those values. I used them for my paper, don't know if they fit with Kuala Lampur though.

**Comment by matthiasdemuzere** [comment]
Of course, the whole idea of WUDAPT is that it provides a first order approximation of urban canopy information, especially for those areas that lack more detailed information. So this is a good starting point.

Since I will introduce a small .csv lookup table in this python module, users can always adjust parameter values if they think/know that they are not fit for their area of interest ....
